from setuptools import setup, find_packages

setup(
    name="quantum-md",
    version="0.1.0",
    description="Quantum Molecular Dynamics for Proteins",
    author="QMD Developer",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "numpy>=1.21.0",
        "scipy>=1.7.0",
        "pyscf>=2.1.0",
        "ase>=3.22.0",
        "mdanalysis>=2.4.0",
        "biopython>=1.80",
        "numba>=0.56.0",
        "matplotlib>=3.5.0",
        "plotly>=5.0.0",
        "py3dmol>=2.0.0",
        "nglview>=3.0.0",
        "pandas>=1.4.0",
        "h5py>=3.6.0",
        "scikit-image>=0.18.0",
    ],
    extras_require={
        "gpu": [
            "cupy-cuda11x>=11.0.0",
            "cupyx>=11.0.0",
            "pyscf[gpu]>=2.1.0",
        ],
        "gpu-cuda12": [
            "cupy-cuda12x>=12.0.0",
            "cupyx>=12.0.0",
            "pyscf[gpu]>=2.1.0",
        ],
        "mpi": ["mpi4py>=3.1.0"],
        "dev": ["pytest>=7.0.0", "black>=22.0.0", "flake8>=4.0.0", "mypy>=0.950"],
        "full": [
            "cupy-cuda11x>=11.0.0",
            "cupyx>=11.0.0",
            "pyscf[gpu]>=2.1.0",
            "mpi4py>=3.1.0",
            "scikit-image>=0.18.0",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)