"""
Electron Density Data Export System
"""

import numpy as np
import h5py
import argparse
from typing import Tuple


class DensityExporter:
    """Export electron density data to various formats."""

    def __init__(self):
        pass

    def load_density_data(self, h5_file: str) -> Tuple[np.ndarray, Tuple[int, int, int]]:
        """Load density data from HDF5 file."""
        with h5py.File(h5_file, 'r') as f:
            density = f['density'][:]
            grid_shape = tuple(f.attrs['grid_shape'])
            total_electrons = f.attrs['total_electrons']

        print(f"Loaded density data: {grid_shape}, Total electrons: {total_electrons:.2f}")
        return density, grid_shape

    def save_cube_file(self, density: np.ndarray, output_file: str,
                      origin: Tuple[float, float, float] = (0.0, 0.0, 0.0),
                      spacing: float = 0.5):
        """Save density data as Gaussian cube file format."""

        nx, ny, nz = density.shape

        with open(output_file, 'w') as f:
            # Header lines
            f.write("Electron density from quantum MD simulation\n")
            f.write("Generated by antibody quantum MD package\n")

            # Number of atoms (0 for grid-only data) and origin
            f.write(f"    0 {origin[0]:12.6f} {origin[1]:12.6f} {origin[2]:12.6f}\n")

            # Grid dimensions and vectors
            f.write(f"{nx:5d} {spacing:12.6f}    0.000000    0.000000\n")
            f.write(f"{ny:5d}    0.000000 {spacing:12.6f}    0.000000\n")
            f.write(f"{nz:5d}    0.000000    0.000000 {spacing:12.6f}\n")

            # Write density data
            count = 0
            for i in range(nx):
                for j in range(ny):
                    for k in range(nz):
                        f.write(f"{density[i,j,k]:13.5e}")
                        count += 1
                        if count % 6 == 0:
                            f.write("\n")
                        else:
                            f.write(" ")

            if count % 6 != 0:
                f.write("\n")

        return output_file

    def save_npy_file(self, density: np.ndarray, output_file: str):
        """Save density data as NumPy binary file."""
        np.save(output_file, density)
        return output_file

    def export_density(self, h5_file: str, cube_file: str = None, npy_file: str = None,
                      spacing: float = 0.5):
        """Export density data to cube and/or npy formats."""

        # Load data
        density, grid_shape = self.load_density_data(h5_file)

        results = []

        # Export to cube format
        if cube_file:
            cube_output = self.save_cube_file(density, cube_file, spacing=spacing)
            results.append(f"Cube file: {cube_output}")

        # Export to npy format
        if npy_file:
            npy_output = self.save_npy_file(density, npy_file)
            results.append(f"NPY file: {npy_output}")

        return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Export electron density data')
    parser.add_argument('--input', '-i', required=True, help='Input HDF5 density file')
    parser.add_argument('--cube', '-c', help='Output cube file')
    parser.add_argument('--npy', '-n', help='Output npy file')
    parser.add_argument('--spacing', '-s', type=float, default=0.5,
                       help='Grid spacing for cube file (Angstrom)')

    args = parser.parse_args()

    if not args.cube and not args.npy:
        print("Error: Must specify at least one output format (--cube or --npy)")
        parser.print_help()
        exit(1)

    exporter = DensityExporter()
    results = exporter.export_density(args.input, args.cube, args.npy, args.spacing)

    for result in results:
        print(result)